### ISSUE TITLE
[BUG]  GPU detected, but no data shown

### ISSUE THREAD

**Issue by DrDomenicoMarson** [orblazer/plasma-applet-resources-monitor#59] opened 2023-08-29 07:37 UTC
### Current Behavior

Thanks for the fantastic widget!
With the recent update (2.10.2), both my GPUs (Nvidia RTX 2080 super and RTX 3080) are correctly detected.
Unfortunately, all the values are displayed as 0 (usage, memory, temperature), in contrast to what I see simply using `nvidia-smi`.
Changing the GPU to monitor doesn't resolve the issue.

### Expected Behavior

The correct values of usage/memory/temperature should be reported

### Steps To Reproduce

My environment

KDE 5.27.4 on Kubuntu 23.04
KDE framework 5.104.0
Qt 5.15.8
Kernel 6.2.0-31
on X11 session
GPU Driver Version: 535.86.05

### Logs

```Text
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Plasma Windowed" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Makes the plasmoid stay alive in the Notification Area, even when the window is closed." msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Force loading the given shell plugin" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "The applet to open." msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Arguments to pass to the plasmoid." msgid_plural: "" msgctxt: ""
kf.plasma.quick: Applet preload policy set to 1
kf.plasma.core: requesting config for "Resources Monitor (fork)" without a containment!
Using KRun from QML is deprecated (since 5.88). Use Qt.openUrlExternally, or the KIO::OpenUrlJob/KIO::ApplicationLauncherJob classes from C++ instead.
qml: 0
```

### Versions

```Markdown
- Widget: 2.10.2
- KDE Plasma: 5.27.4 
- KDE Framework: 5.104.0
```

**Comment by orblazer** [comment] 2023-08-29 08:24
Hello,
The value are set to "0" in graph or is stuck at "..." ?
If that stuck at "..." could you try to replace `triggeredOnStart: true` by `interval: 100` at the next line and restart the widget ? https://github.com/orblazer/plasma-applet-resources-monitor/blob/40e0b59f0152877ea119c6130ec6f1c769fc52f0/package/contents/ui/components/GpuDetector.qml#L66
Thanks.

**Comment by DrDomenicoMarson** [comment] 2023-08-29 08:29
Hi! The value is set to 0 in both graphs and text values for all the parameters!

**Comment by orblazer** [comment] 2023-08-29 08:34
Oh ok, so that is duplicate of https://github.com/orblazer/plasma-applet-resources-monitor/issues/53 and not bug from the widget.

Thanks.

**Closed by orblazer** 2023-08-29 08:34 UTC
Labels: bug
