### ISSUE TITLE
[BUG] Package format issue?

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [orblazer/plasma-applet-resources-monitor#51] opened 2023-05-24 17:07 UTC
### Current Behavior

update manager goes to update the software
error is given

### Expected Behavior

update manager goes to update the software
update installed

### Steps To Reproduce

attempt to update software

### Screenshots

![Screenshot_20230524_130011](https://github.com/orblazer/plasma-applet-resources-monitor/assets/564653/e3de22d1-344f-44d2-96aa-5795a7b2b48f)

### Logs

```Text
N/A
```

### Versions

```Markdown
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.19.0-41-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: AMD Radeon RX 580 Series
```

**Comment by orblazer** [comment] 2023-05-25 11:12
Hello,
I haven't change format between `2.9.0` and `2.10.0`. Maybe this is due to change the code from your side.
For fix that i think you can simply un install and re install the widget.

**Comment by orblazer** [comment] 2023-05-25 14:29
Hum that is weird, maybe try simply install it from discover :shrug:. I never see an similar issue.

**Comment by GM-Script-Writer-62850** [comment] 2023-05-26 02:32
un-installed and installed it without a error

**Comment by GM-Script-Writer-62850** [comment] 2023-05-28 13:04
and now it says i am on 2.9 trying to upgrade to 2.10 with the same issue

where does it store the installed version data?

**Comment by GM-Script-Writer-62850** [comment] 2023-05-30 17:42
only note worth line i can find is this
```
plugin=org.kde.resourcesMonitor-fork
```
any idea where the updater stores plug version data?

**Comment by GM-Script-Writer-62850** [comment] 2023-05-31 03:59
if you can tell me what files you need to replicate this issue let me know

**Comment by orblazer** [comment] 2023-05-31 09:59
> if you can tell me what files you need to replicate this issue let me know

The issue is i can't reproduce your issue with discover, i haven't any error, and i can't really found an similar issue with that.

> any idea where the updater stores plug version data?

The widgets is stored in `~/.local/share/plasma/plasmoids/`.

---

The only things i can suggest is doing update manually by following this steps :

1. removing current installed widget with `rm -rf ~/.local/share/plasma/plasmoids/org.kde.resourcesMonitor-fork`
2. Downloading new release : [resourcesMonitor-fork-2.10.0.plasmoid](https://github.com/orblazer/plasma-applet-resources-monitor/releases/download/v2.10.0/resourcesMonitor-fork-2.10.0.plasmoid)
3. Extracting it with `unzip -d org.kde.resourcesMonitor-fork ~/Downloads/resourcesMonitor-fork-2.10.0.plasmoid` OR extracting the file at `~/.local/share/plasma/plasmoids/org.kde.resourcesMonitor-fork`

**Comment by GM-Script-Writer-62850** [comment] 2023-05-31 13:47
That is the method i have been using to update it... discover does not see the current version number and IDK why
![Screenshot_20230531_094045](https://github.com/orblazer/plasma-applet-resources-monitor/assets/564653/6ee2fbdf-4e87-4005-a99e-27434ca64698)

```
~/.local/share/plasma/plasmoids/org.kde.resourcesMonitor-fork$ tree -a ./
./
├── contents
│   ├── config
│   │   ├── config.qml
│   │   └── main.xml
│   ├── locale
│   │   ├── fr
│   │   │   └── LC_MESSAGES
│   │   │       └── plasma_applet_org.kde.resourcesMonitor-fork.mo
│   │   └── nl
│   │       └── LC_MESSAGES
│   │           └── plasma_applet_org.kde.resourcesMonitor-fork.mo
│   └── ui
│       ├── components
│       │   ├── ApplicationDelegateItem.qml
│       │   ├── AppsDetector.qml
│       │   ├── functions.js
│       │   ├── graph
│       │   │   ├── base
│       │   │   │   ├── ArrayDataSource.qml
│       │   │   │   ├── BaseSensorGraph.qml
│       │   │   │   ├── GraphText.qml
│       │   │   │   ├── SensorGraph.qml
│       │   │   │   └── TwoSensorsGraph.qml
│       │   │   ├── CpuGraph.qml
│       │   │   ├── DisksGraph.qml
│       │   │   ├── GpuGraph.qml
│       │   │   ├── MemoryGraph.qml
│       │   │   └── NetworkGraph.qml
│       │   ├── NetworkInterfaceDetector.qml
│       │   └── sensors
│       │       └── CpuFrequency.qml
│       ├── config
│       │   ├── ConfigAppearance.qml
│       │   ├── ConfigData.qml
│       │   └── ConfigGeneral.qml
│       ├── controls
│       │   ├── ColorSelector.qml
│       │   ├── CustomizableSize.qml
│       │   ├── PredefinedSpinBox.qml
│       │   └── SpinBox.qml
│       └── main.qml
├── metadata.json
└── translate
    ├── fr.po
    ├── nl.po
    ├── README.md
    └── template.pot

15 directories, 32 files
```

```
~/.local/share/plasma/plasmoids/org.kde.resourcesMonitor-fork$ apt-cache policy plasma-discover plasma-desktop plasma-widgets-addons 
plasma-discover:
  Installed: 5.24.7-0ubuntu0.1
  Candidate: 5.24.7-0ubuntu0.1
  Version table:
 *** 5.24.7-0ubuntu0.1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     5.24.4-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
plasma-desktop:
  Installed: 4:5.24.7-0ubuntu0.1
  Candidate: 4:5.24.7-0ubuntu0.1
  Version table:
 *** 4:5.24.7-0ubuntu0.1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     4:5.24.4-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
plasma-widgets-addons:
  Installed: 4:5.24.7-0ubuntu0.1
  Candidate: 4:5.24.7-0ubuntu0.1
  Version table:
 *** 4:5.24.7-0ubuntu0.1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     4:5.24.4-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
```

**Comment by orblazer** [comment] 2023-06-05 00:48
Hum that really sad, and honestly i'm short at things i could try/search to found why this occurred at you and look like no one else.

Sorry for your troubles.

**Comment by orblazer** [comment] 2023-08-28 23:57
Hello,
After i return on the project i have found the issue. `Discover` check `KPackageStructure` property in `metadata.json` and in fact yes i have change it in 50bebb9c40a1e5d58f2ef43565c0a2c3f17ff099 (so in v2.10.1). So that is logic.

For orignal issue, i think its issue related to https://bugs.kde.org/show_bug.cgi?id=448625 (seem caused when `KPackageStructure` was not found) and that is fixed by KDE.

After that constat i can mark this solved and re open it if its not.
Thanks.

**Closed by orblazer** 2023-08-28 23:57 UTC
Labels: bug, help wanted

**Comment by GM-Script-Writer-62850** [comment] 2023-09-03 04:49
so what do i need to change to make the kde updater happy?

it fails to update 2.9.0 to 2.10.2 (2.10.2 has been manually installed)

```
plasma-discover:
  Installed: 5.24.7-0ubuntu0.1
  Candidate: 5.24.7-0ubuntu0.1
  Version table:
 *** 5.24.7-0ubuntu0.1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     5.24.4-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
```

**Comment by orblazer** [comment] 2023-09-03 14:47
Normally since manually update v2.10.1 you should have no longer issues with automatic update.

**Comment by GM-Script-Writer-62850** [comment] 2023-09-03 15:20
Discover does not acknowledge that it has been updated... and fails when trying to update

When i say manually i mean extracting source files to ~/.local/share/plasma/plasmoids/org.kde.resourcesMonitor-fork/`

![image](https://github.com/orblazer/plasma-applet-resources-monitor/assets/564653/f1e60fa3-0397-465f-af42-20a3ee64061b)

**Comment by orblazer** [comment] 2023-09-03 20:08
Hum maybe you can try do uninstall et re install it from Discover :shrug: I never use that software for my knowledge is limited.

**Comment by GM-Script-Writer-62850** [comment] 2023-09-03 20:12
| I never use that software

???

the only one i used was discover...

**Comment by orblazer** [comment] 2023-09-03 20:34
Hum on my manjaro setup i use `org.manjaro.pamac.manager`.

**Comment by GM-Script-Writer-62850** [comment] 2023-09-03 20:40
here is the launcher for the updater on kubuntu
```
$ cat /usr/share/applications/org.kde.discover.desktop |egrep "^\[|Exec"
[Desktop Entry]
Exec=plasma-discover %F
[Desktop Action Updates]
Exec=plasma-discover --mode update
```

**Comment by GM-Script-Writer-62850** [comment] 2024-09-03 19:25
After updating to 24.04 the updates installs, now on 2.11.4 (kubunut 24.04 uses plasma 5) but it is not telling me to update to a version that can not be installed

**Comment by orblazer** [comment] 2024-09-04 16:41
This project have no longer update for Plasma 5.

**Comment by GM-Script-Writer-62850** [comment] 2024-09-12 16:23
I was mainly just letting you know the update issue fixed it self with the OS upgrade
