### ISSUE TITLE
[BUG] CPU usage as text % disappears at 0%

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [orblazer/plasma-applet-resources-monitor#25] opened 2022-01-03 02:40 UTC
**Describe the bug**
 A reading of 0.0% for CPU usage does not appear in the widget, the number appearing/disappearing is distracting

**To Reproduce**

Steps to reproduce the behavior: have a high end enough cpu to see 0.0% usage with a DE running at idle (probably possible with a old high core count xeon)

**Expected behavior**
Widget shows 0.0% or 0%

**Screenshots**

**Versions (please complete the following information):**
Resource monitor (fork): 2.6.2
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.16.0-051600rc8-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: Radeon RX 580 Series

**Additional context**

**Comment by orblazer** [comment] 2022-01-03 11:49
Hello,
Could you try with the last commits for see if that has fix?

**Comment by GM-Script-Writer-62850** [comment] 2022-01-03 15:50
So about this line: `// TODO: stack the graph values for eal fill percent ?`
eal?

applied patch, but i think i need to restart the widget to see if it works while having everything closed, do that next sunday when the next kernel update comes out

**Comment by GM-Script-Writer-62850** [comment] 2022-01-03 16:31
Just tested it on another system, shows '...'  i would rather see '0%', '0.0%', or '>0.1%'

**Comment by orblazer** [comment] 2022-01-04 09:43
Oh ok, i have just miss my basics of JavaScript :facepalm: 

In JS `0 || 'string'` show `string'` and not `0` so i have change my code and now this should work.

**Comment by GM-Script-Writer-62850** [comment] 2022-01-04 13:29
if you think that is bad try python, at least in JS and PHP we have `===`

**Comment by GM-Script-Writer-62850** [comment] 2022-01-10 18:29
is this supposed to be fixed in 2.6.3? if so it is not working

**Comment by orblazer** [comment] 2022-01-10 22:22
That is weird, could you check if that is still the same issue with unreleased version ?

**Comment by GM-Script-Writer-62850** [comment] 2022-01-11 03:18
yea the original issue is back

**Comment by orblazer** [comment] 2022-01-11 10:50
That is really strange, i don't see were its could be come instead nullish values.

Could you try to add some print (sorry i can't reproduce the issue by myself) :
1. Add `print(column, "index not found")` before https://github.com/orblazer/plasma-applet-resources-monitor/blob/52c35ce47f49e679290be80c737cbd185f5f1ff7/package/contents/ui/components/SensorGraph.qml#L26
2. Add `print(column, data(index(0, column), Sensors.SensorDataModel.Name), data(index(0, column), Sensors.SensorDataModel.Value))` before https://github.com/orblazer/plasma-applet-resources-monitor/blob/52c35ce47f49e679290be80c737cbd185f5f1ff7/package/contents/ui/components/SensorGraph.qml#L29

Thanks by advance

**Comment by GM-Script-Writer-62850** [comment] 2022-01-11 16:04
qml: 0 Total Usage 0
qml: 0 Total Usage 0

![Screenshot_20220111_110137](https://user-images.githubusercontent.com/564653/148977920-02ee108d-a230-48e1-81ca-b42a921411a8.png)

**Comment by orblazer** [comment] 2022-01-12 12:50
Ok, i have found the issue its because `libksysguard` return empty string when is "null" value :facepalm:

So this is fixed with `2.7.0`.

**Closed** 2022-01-12 12:51 UTC
Labels: bug
