### ISSUE TITLE
[BUG] text settings (displayment)

### ISSUE THREAD

**Issue by slartibart70** [orblazer/plasma-applet-resources-monitor#16] opened 2021-12-09 10:07 UTC
**Describe the bug**
i'm using 2.5.2 on fc34.
Changing the appearance / text settings while the resources monitor (fork) / rmf is sitting in the taskbar does not refresh the text.
Example: change text displayment between always/on hover/hints on hover and press apply after each item.
There happens to be a state when no text is displayed at all, even when the last setting is selected as 'always'.

**Expected behavior**
apply should do a proper refresh of all visible items in the widget

**Versions (please complete the following information):**

- Version : 
Operating System: Fedora 34
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.15.6-100.fc34.x86_64 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7820HQ CPU @ 2.90GHz
Memory: 31,1 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630

**Additional context**

**Comment by orblazer** [comment] 2021-12-19 14:20
Hello,
Could you try if this is fixed with version `2.5.3` ?

**Comment by GM-Script-Writer-62850** [comment] 2021-12-20 05:40
i am unable to reproduce this on `2.5.3.hotfix.1`
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.16.0-051600rc6-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: Radeon RX 580 Series

**Comment by slartibart70** [comment] 2021-12-20 10:46
Hi,
i have updated to 2.5.3-hotfix.1
The text display is fine now

One thing i discovered:
if you configure 'hints on hover' and the mouse is placed on the widget, then you get the hint-text. 
But, this is effective only on the memory graph, the network and cpu graph will override the hint-text as soon as new values are coming in
Maybe a 'stable' hint text (while hovering) would be better instead?

**Comment by orblazer** [comment] 2021-12-20 20:44
This should be completely fixed with `2.6.0`.

**Closed** 2021-12-20 23:31 UTC
Labels: bug
