### ISSUE TITLE
[BUG] Not detecting GPU

### ISSUE THREAD

**Issue by den7007** [orblazer/plasma-applet-resources-monitor#53] opened 2023-06-17 09:08 UTC
### Current Behavior

Hi, I recently updated to NVIDIA 535.54.03 drivers and just noticed the widget isn't detecting my GPU anymore.

Operating System: EndeavourOS 
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Kernel Version: 6.1.34-1-lts (64-bit)
Graphics Platform: Wayland
Processors: 12 × Intel® Core™ i5-10600K CPU @ 4.10GHz
Memory: 31.2 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3070/PCIe/SSE2
Manufacturer: ASUS

### Expected Behavior

Displays GPU stats

### Steps To Reproduce

This happens at boot or even if I disable/enable, uninstall/reinstall

### Screenshots

![image](https://github.com/orblazer/plasma-applet-resources-monitor/assets/68644291/f125841f-ab55-42aa-beb2-2dd9e4948984)

### Logs

```Text
Jun 17 17:03:42 endeavour-os plasmashell[5864]: QString::arg: 2 argument(s) missing in org.kde.kinfocenter
Jun 17 17:03:42 endeavour-os plasmashell[5864]: org.kde.plasma.notifications: Trying to replace notification with id 1547 which doesn't exist, creating a new one. This is an application bug!
Jun 17 17:03:42 endeavour-os plasmashell[5864]: Could not find the Plasmoid for Plasma::FrameSvgItem(0x5634f77de9f0) QQmlContext(0x5634f423edc0) QUrl("file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml")
Jun 17 17:03:42 endeavour-os plasmashell[5864]: Could not find the Plasmoid for Plasma::FrameSvgItem(0x5634f77de9f0) QQmlContext(0x5634f423edc0) QUrl("file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml")
Jun 17 17:03:54 endeavour-os plasmashell[5864]: org.kde.plasma.notifications: Trying to replace notification with id 1548 which doesn't exist, creating a new one. This is an application bug!
Jun 17 17:03:54 endeavour-os plasmashell[5864]: Could not find the Plasmoid for Plasma::FrameSvgItem(0x5634f6bdb9e0) QQmlContext(0x5634f423edc0) QUrl("file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml")
Jun 17 17:03:54 endeavour-os plasmashell[5864]: Could not find the Plasmoid for Plasma::FrameSvgItem(0x5634f6bdb9e0) QQmlContext(0x5634f423edc0) QUrl("file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml")
Jun 17 17:04:00 endeavour-os plasmashell[5864]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Jun 17 17:04:00 endeavour-os plasmashell[5864]: file:///usr/lib/qt/qml/org/kde/plasma/extras/PlaceholderMessage.qml:238:5: QML Heading: Binding loop detected for property "verticalAlignment"
Jun 17 17:04:00 endeavour-os plasmashell[5864]: file:///usr/lib/qt/qml/org/kde/plasma/extras/PlaceholderMessage.qml:238:5: QML Heading: Binding loop detected for property "verticalAlignment"
Jun 17 17:04:00 endeavour-os plasmashell[5864]: kf.sonnet.core: No language dictionaries for the language: "en_US"
Jun 17 17:04:01 endeavour-os plasmashell[5864]: QString::arg: 2 argument(s) missing in nvidia-settings
Jun 17 17:04:03 endeavour-os plasmashell[5864]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Jun 17 17:04:03 endeavour-os plasmashell[5864]: file:///usr/lib/qt/qml/org/kde/plasma/extras/PlaceholderMessage.qml:238:5: QML Heading: Binding loop detected for property "verticalAlignment"
Jun 17 17:04:03 endeavour-os plasmashell[5864]: file:///usr/lib/qt/qml/org/kde/plasma/extras/PlaceholderMessage.qml:238:5: QML Heading: Binding loop detected for property "verticalAlignment"
Jun 17 17:04:03 endeavour-os plasmashell[5864]: kf.sonnet.core: No language dictionaries for the language: "en_US"
Jun 17 17:04:04 endeavour-os plasmashell[5864]: QString::arg: 2 argument(s) missing in com.leinardi.gwe
Jun 17 17:05:16 endeavour-os plasmashell[5864]: QQmlEngine::setContextForObject(): Object already has a QQmlContext
Jun 17 17:05:16 endeavour-os plasmashell[5864]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/AppletConfiguration.qml:126:5: QML ScrollView: Binding loop detected for property "implicitWidth"
Jun 17 17:05:16 endeavour-os plasmashell[5864]: QQmlEngine::setContextForObject(): Object already has a QQmlContext
Jun 17 17:05:16 endeavour-os plasmashell[5864]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationAppletPage.qml:38:5: QML Loader: Binding loop detected for property "height"
Jun 17 17:05:16 endeavour-os plasmashell[5864]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Jun 17 17:05:16 endeavour-os plasmashell[5864]: file:///usr/share/plasma/plasmoids/org.kde.plasma.battery/contents/ui/CompactRepresentation.qml:61:17: Unable to assign [undefined] to int
Jun 17 17:05:16 endeavour-os plasmashell[5864]: file:///home/den/.local/share/plasma/wallpapers/a2n.blur/contents/ui/WindowModel.qml:23:3: Unable to assign [undefined] to QRect
Jun 17 17:05:16 endeavour-os plasmashell[5864]: file:///usr/share/plasma/plasmoids/org.kde.plasma.printmanager/contents/ui/PrinterItem.qml:22:5: Unable to assign [undefined] to bool
Jun 17 17:05:17 endeavour-os plasmashell[5864]: Both point size and pixel size set. Using pixel size.
Jun 17 17:05:17 endeavour-os plasmashell[5864]: org.kde.plasma.containmentlayoutmanager: Error: cannot change the containment to AppletsLayout
```

### Versions

```Markdown
- Widget: 2.9.1
- KDE Plasma: 5.27.5
- KDE Framework: 5.107.0
```

**Comment by Ir0nyPT** [comment] 2023-06-17 09:43
I'm using in 3 different computers and all have the same issue
Two of them with NVIDIA and other with Intel Graphics

**Comment by denji** [comment] 2023-06-18 02:15
Last working version was for NVIDIA 530, NVIDIA 535 stopped parsing status dGPU.

**Comment by denji** [comment] 2023-06-18 02:30
The process  (`org.kde.ksysguard.sensors`) `kstatsviewer gpu/gpu0/usedVram` is never complete. Not working with NVIDIA 535.

**Comment by denji** [comment] 2023-06-18 02:31
Last working version was for NVIDIA 530, plasma-applet-resources-monitor v2.10.1 stopped NVIDIA 535 parsing status dGPU. The module  (`org.kde.ksysguard.sensors`) `kstatsviewer gpu/gpu0/usedVram` is never complete, the procedure hangs up. Not working with NVIDIA 535.

**Comment by denji** [comment] 2023-06-18 02:56
https://invent.kde.org/plasma/libksysguard/-/blob/Plasma/5.27/processcore/plugins/nvidia/nvidia.cpp?ref_type=heads#L57-82

**Comment by orblazer** [comment] 2023-06-18 14:02
Hello,
This issue is due to wrong sensor because gpu is link on `gpu1` instead of `gpu0`.
But i have make an fix in v2.10.1 for allowing users select they correct graphic card (https://github.com/orblazer/plasma-applet-resources-monitor/commit/c19317233ff1f8aa68fc2f3c3dff352fa95e7430). so please update the package.

**Comment by denji** [comment] 2023-06-18 23:54
@orblazer This fix doesn't help, there's a problem with the parser moudule from the nvidia-smi utility where the `pmon` column indents were changed in NVIDIA version 535. `libksysguard` kills the process without parsing, the `usedVram` value has no default value unlike `usage` / `temperature` this causes the process to crash when `libksysguard` interacts.

**Comment by denji** [comment] 2023-06-19 04:08
@orblazer This is actually an unrelated problem, the new drivers have changed the indents and number of columns for "nvidia-smi pmon" and "nvidia-smi dmon -d 2 -s pucm" which use the KDE toolkit to collect system statistics. The statically hardcoded parser does not get the correct number of columns and indents, so fixing the GPU numbering selection will not help us now.

The bug is relevant again, and requires a library codebase fix.:
* https://invent.kde.org/plasma/libksysguard/-/blob/Plasma/5.27/processcore/plugins/nvidia/nvidia.cpp?ref_type=heads#L57-82
  - `nvidia-smi pmon` v535: https://pastebin.com/raw/ugzfKUTX
* https://invent.kde.org/plasma/ksystemstats/-/blob/Plasma/5.27/plugins/gpu/NvidiaSmiProcess.cpp?ref_type=heads#L159-192
  - `nvidia-smi dmon -d 2 -s pucm` v535: https://pastebin.com/raw/vPCzvxYh
  - https://bugs.kde.org/show_bug.cgi?id=462512

**Comment by orblazer** [comment] 2023-06-20 12:25
@denji ok, so u think the issue look slate until i release v3.x and use new ksysguard version.

**Comment by denji** [comment] 2023-06-20 12:41
@orblazer need a fix in `ksystemstats` (dmon telemetry monitoring for each NVIDIA GPU), `libksysguard` captures statistics (pmon) on GPU processes only.

**Comment by RafaelLinux** [comment] 2023-06-27 22:27
Same here. But I must add than even Plasma "System monitor" is not showing GPU info (always shows zero use) with most applications. Example: When playing games like "Zero-K" or "Metro Redux", "System monitor" is not showing in GPU column any activity.  It shows activity with "CS:GO". I investigated a few more and discovered than only "nvtop" (installed from repositories) shows real GPU activity with all those games. I told this here but didn't notify it still to Plasma developers.

Operating System: openSUSE Tumbleweed 20230621
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Kernel Version: 6.3.7-1-default (64-bit)
Graphics Platform: X11
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2

**Comment by denji** [comment] 2023-06-28 02:42
@RafaelLinux Reading some values causes segfault, there are no default values for nvidia-smi fields, and the required fix is not yet merged by KDE.

```
$ kstatsviewer gpu/gpu0/usage
gpu/gpu0/usage 0
$ kstatsviewer gpu/gpu0/temperature
gpu/gpu0/temperature 0
## "kstatsviewer gpu/gpu0/usedVram" is never complete
$ timeout 10s bash -c "kstatsviewer gpu/gpu0/usedVram"
```

**Comment by RafaelLinux** [comment] 2023-06-28 19:23
So there is a fix but no one knows when it will be available, is it not?

**Comment by denji** [comment] 2023-06-29 06:36
@RafaelLinux This pull request has not yet been approved/merged into the plasma/ksystemstats repository. A fix should appear in 5.27.6+

**Comment by RafaelLinux** [comment] 2023-06-29 07:54
Fortunately, I use openSUSE TW, so I expect fix will be available before 2
months.

Thank you!!!

**Comment by dull4h4n** [comment] 2023-07-17 22:42
This happens for me when using nobara 6.3.11 fsync kernel, but not using anything else. I notice that my video card is detected as "GPU 2", while other kernels recognize it appropriately as GPU 1. I have an amd radeon 6800xt card. Monitor just needs to look for all available cards more broadly.

**Comment by denji** [comment] 2023-08-01 18:27
The problem for NVIDIA is solved KDE Plasma Version: 5.27.7, for AMD look for fixes or not approved merge requests.

**Comment by RafaelLinux** [comment] 2023-08-01 23:12
Thank you for the info!!!! I'll update now!!! ;)

**Comment by orblazer** [comment] 2023-08-16 20:59
Hello,
I close this issue due to the issue seem to be fixed.

**Closed by orblazer** 2023-08-16 20:59 UTC
Labels: bug

**Comment by RafaelLinux** [comment] 2023-08-20 18:31
Yessss!!! It's working (w/o touching nothing, only upgrading my Tumbleweed). Thank you!!

**Comment by RafaelLinux** [comment] 2023-08-20 20:20
Only an additional thing .... GPU still is not selectable. If user click on dropdown button, nothing to select ... it's something weird .... :( ... it works, but that's confusing.

**Comment by orblazer** [comment] 2023-08-20 23:31
> Only an additional thing .... GPU still is not selectable. If user click on dropdown button, nothing to select ... it's something weird .... :( ... it works, but that's confusing.

Ok, i receive my new RTX in few days so i could try to see if the issue is present for me.

**Comment by denji** [comment] 2023-08-21 00:22
@RafaelLinux Select gpu and save option, there is an undefined or incorrect behavior error in the qml code of the "orblazer/plasma-applet-resources-monitor" module. Perhaps there is an empty string "0" instead of qpu{index} or "gpu" instead of "gpu0", "gpu1".

**Comment by denji** [comment] 2023-08-21 00:23
@RafaelLinux Perhaps "orblazer/plasma-applet-resources-monitor" module there is an empty string "0" instead of qpu{index} or "gpu" instead of "gpu0", "gpu1".

**Comment by RafaelLinux** [comment] 2023-08-21 13:01
I imagine you are talking about source code. As user, I can't select or
save explicitly nothing (only "Apply", but nothing to select as you can see
in screenshot).

[image: image.png]

**Comment by orblazer** [comment] 2023-08-27 21:39
@RafaelLinux Hello, your last issue seem similar to https://github.com/orblazer/plasma-applet-resources-monitor/issues/58, so keep an eye on that.

**Comment by RafaelLinux** [comment] 2023-08-28 00:46
> @RafaelLinux Hello, your last issue seem similar to #58, so keep an eye on that.

Ok, I'll put my system info there
