### ISSUE TITLE
[BUG] non-existent property "updateRateLimit" - SensorGraph

### ISSUE THREAD

**Issue by leosenko** [orblazer/plasma-applet-resources-monitor#35] opened 2022-09-23 13:42 UTC
**Describe the bug**
Not Working, says:

Error loading QML file: file:///home/user/.local/share/plasma/plasmoids/org.kde.resourcesMonitor-fork/contents/ui/main.qml:113:5: Type RMComponents.SensorGraph unavailable
file:///home/user/.local/share/plasma/plasmoids/org.kde.resourcesMonitor-fork/contents/ui/components/SensorGraph.qml:23:9: Cannot assign to non-existent property "updateRateLimit"

**To Reproduce**
1. Add widget,
2. it is not working

**Expected behavior**
To work

**Screenshots**

**Versions (please complete the following information):**

- Version : 2.7.1
- KDE Plasma Version : 5.20.5
- KDE Frameworks Version : 5.78.0
- Qt Version : 5.15.2
- Kernel Version : 5.10.0-18-amd64
- OS Type : 64-bit
- Graphics Platform : X11

**Additional context**
Just ordinary debian KDE

**Comment by orblazer** [comment] 2023-04-27 00:41
Hello,
Sorry for the late. The issue is still present ?

**Comment by orblazer** [comment] 2023-05-16 10:35
Hello,
This should be fixed with new versions.

**Closed by orblazer** 2023-05-16 10:35 UTC
Labels: bug
